### PR TITLE
Build native runtimes using github actions

### PR DESCRIPTION
**Pull request by anggape**
this pr related to #8

### CODE REVIEW

**Comment by anggape** [comment]
this need to be tested on windows since i don't have windows machine laying around, but its tested and working on ubuntu, arch linux, and macos

**Comment by jasonswearingen** [comment]
related issue: #8 

Thank you for this!   I will review today.   

Skimming through it is mostly beyond my knowledge, is it possible for you to write up a short maintenance `.md` ?   For things like how to regenerate the libraries, or how to point to specific commits of the sub-modules?   Or how I should go about publishing a new nuget based on these githubaction-based builds?  


If these should all be obvious to anyone working with github actions, sorry...  I have not :(

**Comment by anggape** [comment]
its quiet simple actually you just update raylib submodule > push to github and then run workflows from https://github.com/NotNotTech/Raylib-CsLo/actions/workflows/runtime.yml and run workflows on main branch from there and it will automaticly update linux, macos, and windows library on https://github.com/NotNotTech/Raylib-CsLo/tree/main/Raylib-CsLo/runtimes

**Comment by anggape** [comment]
im actually thinking about separating native library from generated c# code and update the native library daily from raylib master so we can always get the most updated raylib

**Comment by anggape** [comment]
and also automaticly publish to nuget

**Comment by jasonswearingen** [comment]
I actually only barely understand the whole process.  can I give you maintainer permissions here?

also, I'm assuming I could give you publish access to the nuget raylib-cslo package, are you interested?

**Comment by anggape** [comment]
ok, i can do that

**Comment by jasonswearingen** [comment]
ok you should see an invite for maintainer.   also could you let me know your email so I can send you a nuget pub key?   mine is jasons at novaleaf dot com

**Comment by anggape** [comment]
i think some people on discord doesn't agree separating raylib-cslo into separate package, so this changes is ready to merge

**Comment by anggape** [comment]
just ping me when you need something

**Comment by jasonswearingen** [comment]
todo:  it would be good to pull this into a new branch to test and get working.  then merge into master.

**Pull request closed without merging**
