### PR TITLE
Safe codegen

### PR DESCRIPTION
**Pull request by IrishBruse**
# W.I.P

Using the `Raylib-CsLo\sub-modules\raylib\parser\raylib_api.json` i can do some code generation with c# to make the C# class

What do you think about moving all safe code to a `RaylibS` class as I have found the overloads a bit messy with intellisense

### CODE REVIEW

**Comment by jasonswearingen** [comment]
I'm not familar with Code Generators, but this looks really cool!    I will look through the code this morning and write more comments.

**Comment by IrishBruse** [comment]
It also should be possible to remove clangsharp and just generate all the bindings ourselves once I get more of this done. I also have added intellisense documentation generation.

**Comment by jasonswearingen** [comment]
It's really hard for me to code review via GitHub, so I just accepted all PR's and am reviewing from my git client (Fork).

- **Code Style**
  - **Disuse of `var`**:  You switch from `var` to explicitly declaring the type, such as `var toReturn = GetGamepadName(gamepad);` to `sbyte* toReturn = GetGamepadName(gamepad);`      I strongly prefer leaving `var` for ease of refactoring.    **I won't undo this change though, as I don't expect to need to refactor this code often/at all.**.  It's easier to just conform to all your code style for this I expect.
  - **Private variables** I am in the "prefix private variables" camp, but okay to just conform to your codestyle for this project
- **Rename of overload properties** You rename overload properties like `	public CameraProjection projection_` to `public CameraProjection Projection`   Again just easy to keep your style, but this introduces a breaking change to the API so I should hold off on a new (release) nuget package until we are sure the api is stable.  I can publish as a preview version though, so I will do that today.  Also related is modification of the Readme.md to change the tip on overloads.  I'll do that.
- **CodeGen** will need to run this (planning today) to give more feedback

**Comment by IrishBruse** [comment]
- The code style was one I found online and matched pretty well with how I program I have made a good few changes to it and am always changing it so we can update it as we go if we need to.
    - I use `var` for programming and VsCode when I hit save automatically resolves it to the variable type I like as it means i dont have to hover over a variable to know its type and makes looking through code alot easier to read. it as It enforces the use of `new()` which is great for Dictionaries we need to clarify the type somewhere or else it might give errors very rarely. I do have to admit it does get ugly in foreach loops like in the code gen over the keyvaluepair but i think i just need to refactor that anyways.
- The _ at the end is somewhat confusing as its abit inconsistent and by doing the RaylibS it should fix those issues.
- Im still rather far out from it fully workinig but its coming along alot faster than I was expecting it to :)

**Comment by IrishBruse** [comment]
Sorry the pull request isnt done yet you should probably hard reset i also need to rebase anyways merging it i dont know how to mark a pull request as a draft and mostly just wanted any feedback on this you could give.

**Comment by jasonswearingen** [comment]
> It also should be possible to remove clangsharp and just generate all the bindings ourselves once I get more of this done. I also have added intellisense documentation generation.

How do I run the codegen?  it looks like I need to build the exe and then put it in the solution root, then run?   What are the expected outputs?    (it looks like code written to `Raylib-CsLo//autogen/wrappers`)

> What do you think about moving all safe code to a RaylibS class as I have found the overloads a bit messy with intellisense

I don't agree.  I think it's important to leave the safe overloads mixed in, as it aids in discovery for those who need it the most.  Also for me it's important to be able to keep the examples as close to the original C code as possible.   Putting the overloads into another class/namespace further abstracts the examples from the original C (admitidely only a little).   **However**, if you wish to have an "unsafe only" version that would be fine, as it would be simple to dupe the emitted bindings into a namespace something like `Raylib_CsLo.RawBindings`.  I know dupe code is frowned upon, but as these would both be auto generated I don't think the dupe code is an issue.

> Sorry the pull request isnt done yet you should probably revert merging it i dont know how to mark a pull request as a draft and mostly just wanted any feedback on this you could give.

I think it's fine.   From what I can tell, the `Codegen` project doesn't interfere with anything.   I don't know an easier way of reviewing the code other than pulling it (though in hindsight, maybe I should have tried checking out your repo)    To mitigate this I think I'll add a `release` branch, so that we can use the `main` as dev/collaborative and isolate that churn from what's shipped in the nuget package.

FYI I tried out the codegen and it "works" though obviously with incomple/broken codegen.   I personally think that the C# based codegen is unnessicary, as I am happy with the current ClangSharp workflow.   As I'm sure you have seen in the binding gen script, I was barely able to get ClangSharp to meet the minimum requirements for Raylib binding gen, and only by doing some hacky script-based-fixes afterward.   

**That said**, this line of research and generate the bindings via C# CodeGen is great! I would be happy to support you in whatever way I can.   I have never done C# CodeGen but I do agree that it is very promising and long-term, the "best" solution for bindings like raylib.

**Comment by IrishBruse** [comment]
Im using `dotnet watch run --project /Raylib-CsLo.Codegen/Raylib-CsLo.Codegen.csproj`
for live updating of the bindings as I'm coding pretty handy we can come up with some other way to run it later for rn im just trying to get it up and running.

I feel like it makes more sense to seperate the completely unsafe binding and safe bindings as the auto gen generates safe copyies of all the functions again tho we can work out the issues once its working they should be easy enough to customize

**Pull request merged**
