### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by IrishBruse**
- I went and added a better .editorconfig and made changed to suit the project 
- Updated the bindings to use the proper commit with submodules 
- Cleaned up alot of the code that was now giving errors.
- All tests still pass

### CODE REVIEW

**Comment by jasonswearingen** [comment]
Hi @IrishBruse I am happy for your contributions!!!  can you please make sure that whatever you do, the native raylib.dll process and binding gen round-trip still works?    I tried to document it in the powershell script https://github.com/NotNotTech/Raylib-CsLo/blob/main/binding-gen/regen.ps1 and also in that folder `readme.md`

The reason for this, is that for me, the key requirement is that when there are (future) changes to the native raylib.dll, that it is very easy to detect breaking changes (and thus, to fix them).

I will find time tonight or tomorrow morning to do a code review.

**Comment by IrishBruse** [comment]
So for the binding gen I have ran it and it works and regenerates everything but with some warnings I don't how fix these if they are an issue
image

**Comment by jasonswearingen** [comment]
I went ahead and code reviewed via the web, everything looks good.

> So for the binding gen I have ran it and it works and regenerates everything but with some warnings I don't how fix these if they are an issue 

The binding gen warnings look fine (known issues with malloc I mentioned in the readme), but I will compare with my baseline when I build/deploy the nuget package later today.

**Comment by IrishBruse** [comment]
I'm gonna make a new commit I some how managed to completely screw up my branch lol.

**Pull request closed without merging**
